version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.8
      
    working_directory: /go/src/github.com/supcik/ws2811
    steps:
      - run:
          name: Building and installing C librairie
          command: |
            sudo apt-get install build-essential git scons curl
            echo "deb http://emdebian.org/tools/debian/ jessie main" | sudo tee /etc/apt/sources.list.d/crosstools.list
            curl http://emdebian.org/tools/debian/emdebian-toolchain-archive.key | sudo apt-key add -
            sudo dpkg --add-architecture armhf
            sudo apt-get update
            sudo apt-get install crossbuild-essential-armhf
            mkdir -p ${HOME}/src/lib
            cd ${HOME}/src/lib
            git clone https://github.com/jgarff/rpi_ws281x.git
            cd rpi_ws281x
            git reset --hard 389f074e41f41ed7b5e9b8c7a2fd06ccfa3a2eaa
            curl https://patch-diff.githubusercontent.com/raw/jgarff/rpi_ws281x/pull/213.diff | patch
            curl https://patch-diff.githubusercontent.com/raw/jgarff/rpi_ws281x/pull/214.diff | patch
            scons TOOLCHAIN=arm-linux-gnueabihf
            sudo mkdir -p /usr/local/lib
            sudo cp *.a /usr/local/lib
            sudo mkdir -p /usr/local/include
            sudo cp *.h /usr/local/include
      - checkout
      - run: go get -u github.com/alecthomas/gometalinter
      - run: gometalinter --install
      - run: sudo chown -R circleci:circleci /usr/local/go/pkg
      - run:
          name: Building librarie
          command: |
            go get -v ./...
            go build
          environment:
            GOOS: "linux"
            GOARCH: "arm"
            CGO_ENABLED: 1
            CC: arm-linux-gnueabihf-gcc
            CC_FOR_TARGET: arm-linux-gnueabihf-gcc
            CXX_FOR_TARGET: arm-linux-gnueabihf-g++
            CPATH: /usr/local/include
            LIBRARY_PATH: /usr/local/lib
      - store_artifacts:
          path: /go/pkg/linux_arm/github.com/supcik/ws2811.a
